### ISSUE TITLE
I can't build this source

### ISSUE THREAD

**Issue by lovebdsobuj** [andrewsarnold/FlagMaker-2#1]
Dear sir, Respect with my love. 
I use FlagMaker 1.7, Very nice software. I love it so much. 

What's new in this version 2? 

I'm trying to build this source with my Netbeans, but not yet done.

**Comment by andrewsarnold** [comment]
The only thing new with version 2 is that since it's in Java, it will be usable on Linux and Mac platforms in addition to Windows. There aren't any other new main features implemented yet.

**Comment by lovebdsobuj** [comment]
How can I make Windows run able with this source?

Can I add/make more Custom char in Overlays section eg: ukraine.ovr

Can you add Text add options in this version 2? This features help us
to write Country name.
