### ISSUE TITLE
Localization issue preventing startup on Windows 8.1 64bit

### ISSUE THREAD

**Issue by DrCastle** [andrewsarnold/FlagMaker-2#17]
Hi,

I had the following issue which was discussed on reddit and found out that it is somehow related to the localization of the host, which required an according bundle for the strings.

Error when starting
"This application was configured to use a bundled Java Runtime Environment but the runtime is missing or corrupted."

I opened the project in Netbeans and made copy of the english string bundle, calling it "strings_de.properties" since I'm running the application on a German localized host. After that the build was working fine and the application started.

Hope that helps to fix the starting issue.

PS: Great tool by the way, thanks!

Best regards

**Comment by andrewsarnold** [comment]
Hey, thanks for looking at this. I pulled up the source (haven't looked at it in ages) and I noticed that there already was a German localization, added over a year ago. Did you have the latest version of the code when you tried this?

**Comment by DrCastle** [comment]
Hi, I used the "Download as ZIP" functionality, I hoped that would give me the latest version. I'm not used to Github though, maybe I looked at the wrong location :-S
It got me the properties files at "/FlagMaker/src/bundles/", which doesn't feature a German localization file.

**Comment by andrewsarnold** [comment]
Ah, that's because the "download ZIP" button gets you what's in the master branch, but the German localization is currently only in the develop branch.

I'm hoping to be able to test what's in develop on my Linux machine soon so I can pull that all into master and do a 2.1 release, which should fix all the localization issues people have been having.

**Comment by DrCastle** [comment]
Ah, thanks for the clarification. I guess the issue can be closed then.
