### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by lovebdsobuj** [andrewsarnold/FlagMaker-2#2]
```javac: invalid target release: 1.8```
```Usage: javac <options> <source files>```
```use -help for a list of possible options```

> F:\NetbeansProject\FlagMaker-2\FlagMaker\nbproject\build-impl.xml:938: The following error occurred while executing this line:
> F:\NetbeansProject\FlagMaker-2\FlagMaker\nbproject\build-impl.xml:261: Compile failed; see the compiler error output for details.

BUILD FAILED (total time: 0 seconds)

**Comment by andrewsarnold** [comment]
You'll have to install [JDK 8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html).

**Comment by lovebdsobuj** [comment]
I have installed **JDK 8** but problem is still appear same.

**Comment by lovebdsobuj** [comment]
Sir, My problem is solved, I need to manually edit **netbeans.conf** to set **JDK 8** as defuult Java JDK.
