### ISSUE TITLE
Toggle Texture Not Work!

### ISSUE THREAD

**Issue by lovebdsobuj** [andrewsarnold/FlagMaker-2#3]
Toggle Texture Not Work! Both in 1.7 and 2.0 Version.
![00114_screenshot_at_15h01m43s_001_](https://cloud.githubusercontent.com/assets/10352682/10842057/f0d2695e-7f18-11e5-8ccb-c49acbae5c96.png)

**Comment by andrewsarnold** [comment]
This is intentional behavior.
