### ISSUE TITLE
Cannot detect the Java Runtime Environment

### ISSUE THREAD

**Issue by Keyacom** [andrewsarnold/FlagMaker-2#30]
When opening the program, this error appears:

![Java Runtime Environment detection error](https://user-images.githubusercontent.com/70766223/97087215-ac4a8580-1628-11eb-9876-2efea364254c.png)

### Device's system details
Lenovo g50-70, Windows 10 64-Bit (10.0.19041)

I want to use FlagMaker 2.0.1, and I have the required Java Runtime Environment installed.

**Comment by bc-185** [comment]
It means just what it says. The bundled JRE is missing, and the app won't launch unless you configure it to. This is how to bypass that problem.

1. Right click on any Java shortcut in the Start Menu. (ex. About Java)
2. Go to more, then select Open File Location
3. Right click on the shortcut again
4. Select Open File Location. You should now be in the bin of your Java installation.
5. Hold Shift and Right Click on javaw.exe (javaw if you have file extensions hidden)
6. Select Copy as path
7. Open the Start Menu, then select the FlagMaker folder
8. Right click on the FlagMaker shortcut
9. Go to more, then select Open File Location
10. Right click on the shortcut again
11. Select Properties
12. At the back of the Target, paste in the path that you copied, then add ` -jar `
13. Hit OK.
14. If you like, you can right click on the shortcut again and select Change Icon to change it back to the FlagMaker icon.

**Comment by Keyacom** [comment]
**Thank you so much for your response.**

**Comment by aefsk** [comment]
doents worked, is a very complicated
