### ISSUE TITLE
Color pallet management

### ISSUE THREAD

**Issue by ReeseGlidden** [andrewsarnold/FlagMaker-2#5]
As is, creating custom colors is a bit of a pain, since 'saving' a color only saves is for that color chooser. Ideally once a user selects a color for any flag element, that color should be easily reused elsewhere on that design. Possible solutions include sharing saved colors between color pickers, maintaining a pallet of colors currently used in that design (at the top of the swatches panel in the color picker, for instance), or implementing an eye-dropper tool for selecting colors from existing elements.

**Comment by andrewsarnold** [comment]
Resolved with commit [8fe24fd](https://github.com/andrewsarnold/FlagMaker-2/commit/8fe24fdf467ba6991c960f89d9b572a9808c6f7b)

**Comment by andrewsarnold** [comment]
Resolved with commit [8fe24fd](https://github.com/andrewsarnold/FlagMaker-2/commit/8fe24fdf467ba6991c960f89d9b572a9808c6f7b)
