### ISSUE TITLE
The source code has no license

### ISSUE THREAD

**Issue by psy-q** [andrewsarnold/FlagMaker-2#9]
Which license will this project use?

**Comment by andrewsarnold** [comment]
Never thought about it. Do you have any suggestions?

**Comment by ReeseGlidden** [comment]
Depends on what you want. The MIT license is a good 'I resever no rights'
license

**Comment by psy-q** [comment]
[This](http://choosealicense.com/) has a pretty good overview, but MIT is good if you want to be as permissive as possible while still getting attribution and being a bit protected from liability. "Software provided as is, absolutely no warranty" etc. Who knows what damage a flag maker could possibly do, but in today's world...

**Comment by ReeseGlidden** [comment]
Correct me if I'm wrong but MIT doesn't require attribution?

**Comment by psy-q** [comment]
It must include "Copyright [year] [fullname]" and this:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

I took that to be attribution :)

**Comment by andrewsarnold** [comment]
That should work. Thanks guys!
